// Code generated by "stringer -type Glom -linecomment"; DO NOT EDIT.

package nuggit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GlomUndefined-0]
	_ = x[GlomAssign-1]
	_ = x[GlomAppend-2]
	_ = x[GlomExtend-3]
}

const _Glom_name = "assignappendextend"

var _Glom_index = [...]uint8{0, 0, 6, 12, 18}

func (i Glom) String() string {
	if i < 0 || i >= Glom(len(_Glom_index)-1) {
		return "Glom(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Glom_name[_Glom_index[i]:_Glom_index[i+1]]
}
