// Code generated by "stringer -type CondOp -linecomment"; DO NOT EDIT.

package v1alpha

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CondUndefined-0]
	_ = x[CondPassthrough-1]
	_ = x[CondTrue-2]
	_ = x[CondEqual-3]
	_ = x[CondLess-4]
}

const _CondOp_name = "passthroughtrueequalless"

var _CondOp_index = [...]uint8{0, 0, 11, 15, 20, 24}

func (i CondOp) String() string {
	if i < 0 || i >= CondOp(len(_CondOp_index)-1) {
		return "CondOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CondOp_name[_CondOp_index[i]:_CondOp_index[i+1]]
}
