// Code generated by "stringer -linecomment -type ExprFlags"; DO NOT EDIT.

package v1alpha

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExprFlagsNone-0]
	_ = x[ExprFlagsCaseInsensitive-1]
	_ = x[ExprFlagsMultiLine-2]
	_ = x[ExprFlagsDotAll-4]
}

const (
	_ExprFlags_name_0 = "im"
	_ExprFlags_name_1 = "s"
)

var (
	_ExprFlags_index_0 = [...]uint8{0, 0, 1, 2}
)

func (i ExprFlags) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _ExprFlags_name_0[_ExprFlags_index_0[i]:_ExprFlags_index_0[i+1]]
	case i == 4:
		return _ExprFlags_name_1
	default:
		return "ExprFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
