// Code generated by "stringer -type FnOp -linecomment"; DO NOT EDIT.

package v1alpha

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FnUndefined-0]
	_ = x[FnPassthrough-1]
	_ = x[FnFilter-2]
	_ = x[FnMap-3]
	_ = x[FnFlatMap-4]
	_ = x[FnReduce-5]
	_ = x[FnHead-6]
	_ = x[FnTail-7]
}

const _FnOp_name = "passthroughfiltermapflatmapreduceheadtail"

var _FnOp_index = [...]uint8{0, 0, 11, 17, 20, 27, 33, 37, 41}

func (i FnOp) String() string {
	if i < 0 || i >= FnOp(len(_FnOp_index)-1) {
		return "FnOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FnOp_name[_FnOp_index[i]:_FnOp_index[i+1]]
}
