// Code generated by "stringer -type NumericOp -linecomment"; DO NOT EDIT.

package v1alpha

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NumericOpUnknown-0]
	_ = x[NumericOpPassthrough-1]
	_ = x[NumericOpAdd-2]
}

const _NumericOp_name = "passthroughadd"

var _NumericOp_index = [...]uint8{0, 0, 11, 14}

func (i NumericOp) String() string {
	if i < 0 || i >= NumericOp(len(_NumericOp_index)-1) {
		return "NumericOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NumericOp_name[_NumericOp_index[i]:_NumericOp_index[i+1]]
}
