// Code generated by "stringer -type ReplaceOp -linecomment"; DO NOT EDIT.

package v1alpha

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReplaceUndefined-0]
	_ = x[ReplaceByte-1]
}

const _ReplaceOp_name = "byte"

var _ReplaceOp_index = [...]uint8{0, 0, 4}

func (i ReplaceOp) String() string {
	if i < 0 || i >= ReplaceOp(len(_ReplaceOp_index)-1) {
		return "ReplaceOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReplaceOp_name[_ReplaceOp_index[i]:_ReplaceOp_index[i+1]]
}
