// Code generated by "stringer -type StringOp -linecomment"; DO NOT EDIT.

package v1alpha

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StringUndefined-0]
	_ = x[StringIdentity-1]
	_ = x[StringAggstring-2]
	_ = x[StringIndex-3]
	_ = x[StringSubstring-4]
	_ = x[StringToLower-5]
	_ = x[StringToUpper-6]
	_ = x[StringURLEncode-7]
	_ = x[StringURLDecode-8]
	_ = x[StringURLPathEscape-9]
	_ = x[StringURLPathUnescape-10]
	_ = x[StringURLQueryEscape-11]
	_ = x[StringURLQueryUnescape-12]
}

const _StringOp_name = "identityaggstringindexsubstringtolowertoupperurlencodeurldecodeurlpathescapeurlpathunescapeurlqueryescapeurlqueryunescape"

var _StringOp_index = [...]uint8{0, 0, 8, 17, 22, 31, 38, 45, 54, 63, 76, 91, 105, 121}

func (i StringOp) String() string {
	if i < 0 || i >= StringOp(len(_StringOp_index)-1) {
		return "StringOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StringOp_name[_StringOp_index[i]:_StringOp_index[i+1]]
}
