// Code generated by "stringer -type TimeOp -linecomment"; DO NOT EDIT.

package v1alpha

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TimeUndefined-0]
	_ = x[TimeCurrent-1]
	_ = x[TimeYear-2]
}

const _TimeOp_name = "currentyear"

var _TimeOp_index = [...]uint8{0, 0, 7, 11}

func (i TimeOp) String() string {
	if i < 0 || i >= TimeOp(len(_TimeOp_index)-1) {
		return "TimeOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimeOp_name[_TimeOp_index[i]:_TimeOp_index[i+1]]
}
